-- Task 1
SELECT * FROM CITY WHERE ID = 1661

-- Task 2
SELECT * FROM CITY WHERE COUNTRYCODE = 'USA' AND POPULATION > 100000

-- Task 3
SELECT * FROM CITY WHERE COUNTRYCODE = 'JPN'

-- Task 4
SELECT NAME FROM CITY WHERE COUNTRYCODE = 'JPN'

-- Task 5
SELECT CITY, STATE FROM STATION

-- Task 6
SELECT DISTINCT CITY FROM STATION WHERE ID % 2 = 0

SELECT COUNT(CITY) - COUNT(DISTINCT CITY) FROM STATION

-- Task 7
SELECT TOP 1 CITY, LEN(CITY) FROM STATION ORDER BY LEN(CITY) DESC, CITY ASC;
SELECT TOP 1 CITY, LEN(CITY) FROM STATION ORDER BY LEN(CITY) ASC, CITY ASC;

-- Task 8
SELECT DISTINCT CITY FROM  STATION WHERE CITY REGEXP '^[aeiou]'

-- Task 9
SELECT DISTINCT CITY FROM STATION WHERE CITY REGEXP '[aeiou]$'

-- Task 10
SELECT DISTINCT CITY FROM STATION WHERE CITY REGEXP '^[aeiou]|[aeiou]$'

